import { COMPONENTS } from "./library";
import { componentPreview } from "./previews";
/** Original IDÆVIA examples informed by the linked references; no third-party source is bundled. */
export const COMPONENT_SOURCES = [
  { id: "anime", name: "Anime.js", url: "https://animejs.com/", description: "Timelines, staggered motion, springs, scroll and SVG animation.", note: "Native motion adaptations; the Anime.js runtime is not required." },
  { id: "orb", name: "Liquid Orb", url: "https://lersent001.github.io/orb/", description: "Expressive orbs for voice interfaces, AI assistants and hero visuals.", note: "CSS orb studies. Open the original editor for its WebGPU renderer and export tools." },
  { id: "glass", name: "Liquid Glass", url: "https://glass.samasante.com/", description: "Translucent surfaces, navigation, switches and sliders.", note: "CSS frosted-glass adaptations, without the original optical refraction renderer." },
  { id: "loaders", name: "Circle Loaders", url: "https://circleloaders.dominikakissi.com/", description: "Circular motion for loading, thinking, listening and progress states.", note: "Original SVG/CSS loaders inspired by the circular status-animation collection." },
  { id: "threeui", name: "ThreeUI", url: "https://threeui.com/", description: "Spatial interfaces, 3D objects and atmospheric shader backgrounds.", note: "Original CSS 3D and WebGL studies. No ThreeUI Pro source is included." },
] as const;
export type ComponentSource = typeof COMPONENT_SOURCES[number]["id"];
export type ComponentCategory = "Motion" | "Orbs" | "Glass" | "Loaders" | "3D & shaders";
export interface ComponentExample { id: string; name: string; description: string; category: ComponentCategory; source: ComponentSource; technology: string; html: string; prompt: string }

const base = `*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:#090b12;color:#edf0fa;font:14px/1.5 system-ui,sans-serif}body{overflow-x:hidden}button,input{font:inherit}button{cursor:pointer;color:inherit;background:#ffffff12;border:1px solid #ffffff25;padding:9px 16px;border-radius:99px}button:focus-visible,a:focus-visible,input:focus-visible{outline:2px solid #b5b8ff;outline-offset:4px}.stage{min-height:100dvh;display:flex;align-items:center;justify-content:center;gap:18px;flex-direction:column;padding:24px;position:relative;isolation:isolate;overflow:hidden}h1,h2,p{margin:0}h2{font-size:20px;letter-spacing:-.04em}.caption{font-size:11px;color:#a3aec7;letter-spacing:.08em;text-transform:uppercase}.row{display:flex;gap:12px;align-items:center;justify-content:center}.surface{border:1px solid #ffffff25;border-radius:20px;background:#ffffff09;padding:22px}.muted{color:#a3aec7}svg{max-width:100%}a{color:inherit}button:hover{background:#ffffff24}@keyframes spin{to{transform:rotate(360deg)}}@keyframes breathe{50%{transform:scale(.88);opacity:.4}}@keyframes rise{from{transform:translateY(22px);opacity:0}to{transform:translateY(0);opacity:1}}`;

function demo(name: string, body: string, css = "", js = "") {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data:; base-uri 'none'; form-action 'none'"><title>${name}</title><style>${base}${css}\n@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}}html[data-paused] *,html[data-paused] *::before,html[data-paused] *::after{animation-play-state:paused!important}</style></head><body><main class="stage">${body}</main><script>const reduced=matchMedia('(prefers-reduced-motion: reduce)');document.addEventListener('visibilitychange',()=>{document.documentElement.toggleAttribute('data-paused',document.hidden);});${js}</script></body></html>`;
}

function example(id: string, name: string, description: string, category: ComponentCategory, source: ComponentSource, technology: string, html: string): ComponentExample {
  return { id, name, description, category, source, technology, html, prompt: `Add the ${name} component to my project: ${description} Match my existing design, preserve working features, respect reduced motion, and keep it responsive. [COMPONENT:${id}]` };
}

const motion: ComponentExample[] = [
  example("motion-stagger", "Stagger grid", "A ripple of tiles that unfolds from the center. Replay to explore the timing.", "Motion", "anime", "CSS animation", demo("Stagger grid", `<div class="tiles">${Array.from({ length: 25 }, (_, i) => `<i style="--delay:${(Math.abs(i % 5 - 2) + Math.abs(Math.floor(i / 5) - 2)) * 90}ms"></i>`).join("")}</div><button id="replay">Replay wave</button>`, `.tiles{display:grid;grid-template-columns:repeat(5,23px);gap:7px}.tiles i{height:23px;background:#afa7ff;border-radius:6px;animation:tile 2s var(--delay) infinite both}@keyframes tile{0%,100%{transform:scale(.55) rotate(-12deg);opacity:.2}45%{transform:scale(1) rotate(0);opacity:1}}`, `document.querySelector('#replay').onclick=()=>{for(const a of document.getAnimations())a.currentTime=0};`)),
  example("motion-spring", "Spring interaction", "Drag the handle, then release it to spring back. Arrow keys work too.", "Motion", "anime", "Web Animations", demo("Spring interaction", `<div class="rail"><button id="handle" aria-label="Drag spring handle or use arrow keys">↔</button></div><span class="caption">Drag · release · repeat</span>`, `.rail{width:min(260px,80vw);height:65px;border-radius:40px;border:1px dashed #6e6988;display:grid;place-items:center}#handle{width:55px;height:55px;padding:0;background:#b7a4ff;color:#141023;touch-action:none;font-size:24px}`, `const h=document.querySelector('#handle');let origin=0,offset=0;const move=x=>{offset=Math.max(-95,Math.min(95,x));h.style.transform='translateX('+offset+'px)'};const release=()=>{const x=offset;h.style.transform='';offset=0;if(!reduced.matches)h.animate([{transform:'translateX('+x+'px)'},{transform:'translateX('+(-x*.18)+'px)',offset:.65},{transform:'translateX(0)'}],{duration:650,easing:'cubic-bezier(.2,.7,.3,1)'})};h.onpointerdown=e=>{for(const a of h.getAnimations())a.cancel();origin=e.clientX;h.setPointerCapture(e.pointerId)};h.onpointermove=e=>{if(h.hasPointerCapture(e.pointerId))move(e.clientX-origin)};h.onpointerup=e=>{h.releasePointerCapture(e.pointerId);release()};h.onpointercancel=release;h.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();move(e.key==='ArrowLeft'?-85:85)}};h.onkeyup=release;`)),
  example("motion-draw", "Drawn path", "A luminous SVG stroke traces a flowing route.", "Motion", "anime", "SVG + CSS", demo("Drawn path", `<svg width="270" height="110" viewBox="0 0 270 110" role="img" aria-label="Animated flowing path"><path d="M10 90 C50 90 40 15 88 20 S140 110 180 75 S215 5 260 25" fill="none" stroke="#292b3e" stroke-width="3"/><path class="trace" pathLength="1" d="M10 90 C50 90 40 15 88 20 S140 110 180 75 S215 5 260 25" fill="none" stroke="#b8adff" stroke-linecap="round" stroke-width="4"/></svg><span class="caption">Motion in one continuous line</span>`, `.trace{stroke-dasharray:1;animation:draw 4s ease-in-out infinite}@keyframes draw{0%,10%{stroke-dashoffset:1}65%,85%{stroke-dashoffset:0}100%{stroke-dashoffset:-1}}`)),
  example("motion-type", "Word reveal", "A measured word-by-word entrance for a short headline.", "Motion", "anime", "CSS animation", demo("Word reveal", `<h2 aria-label="Make room for possibility.">${["Make", "room", "for", "possibility."].map((w, i) => `<span aria-hidden="true" style="animation-delay:${i * 130}ms">${w} </span>`).join("")}</h2><button id="replay">Replay headline</button>`, `h2{max-width:290px;font-size:38px;line-height:1.1;text-align:center}h2 span{display:inline-block;animation:rise .8s both;color:#e4ddff}`, `document.querySelector('#replay').onclick=()=>{for(const a of document.getAnimations())a.currentTime=0};`)),
  example("motion-timeline", "Sequenced steps", "Three steps illuminate in sequence for onboarding and process explanations.", "Motion", "anime", "CSS timeline", demo("Sequenced steps", `<div class="row">${["Explore", "Build", "Launch"].map((n, i) => `<div class="step" style="--i:${i}"><span>0${i + 1}</span><p>${n}</p></div>`).join("")}</div><span class="caption">One step leads to the next</span>`, `.step{border-top:2px solid #c3afff;padding:12px 14px;background:#ffffff06;animation:step 4.5s infinite;animation-delay:calc(var(--i)*1.5s)}.step span{color:#baa9ff;font-size:11px}.step p{font-size:14px}@keyframes step{0%,33%{opacity:1;transform:translateY(-5px)}40%,100%{opacity:.35;transform:translateY(0)}}`)),
  example("motion-scroll", "Scroll reveal", "Cards appear as they enter a scrollable panel. Scroll inside the preview.", "Motion", "anime", "IntersectionObserver", demo("Scroll reveal", `<div class="scroller" tabindex="0" aria-label="Scroll to reveal cards">${["Scroll to explore ↓", "Purposeful motion", "A little breathing room", "A clear next step"].map((s) => `<div class="reveal surface"><h2>${s}</h2><p class="muted">Less noise. More intention.</p></div>`).join("")}</div>`, `.scroller{width:min(300px,100%);height:180px;overflow:auto;display:grid;gap:20px;padding:5px}.reveal{min-height:135px;transition:opacity .6s,transform .6s}.pending{opacity:.15;transform:translateY(12px)}`, `const root=document.querySelector('.scroller');if(!reduced.matches){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.remove('pending');observer.unobserve(e.target)}}),{root,threshold:.5});document.querySelectorAll('.reveal').forEach(el=>{el.classList.add('pending');observer.observe(el)});reduced.addEventListener('change',()=>{if(reduced.matches){observer.disconnect();document.querySelectorAll('.pending').forEach(el=>el.classList.remove('pending'))}})}`)),
];

const orbs = [
  ["aurora", "Aurora orb", "#38efc3", "#7865fc", "#235aff"],
  ["chrome", "Chrome orb", "#f4f7fa", "#74808e", "#17212c"],
  ["plasma", "Plasma orb", "#ff6fac", "#6738da", "#fa592f"],
  ["voice", "Voice orb", "#ae8bff", "#5097ff", "#e273da"],
].map(([id, name, a, b, c]) => example(`orb-${id}`, name, id === "voice" ? "Switch between idle and listening states for a voice-assistant visual." : "A softly moving, layered orb for an expressive product hero.", "Orbs", "orb", "CSS orb study", demo(name, `<div class="orb" aria-hidden="true"><i></i></div>${id === "voice" ? '<button id="listen" aria-pressed="false">Start listening demo</button><span id="status" class="caption" role="status">Idle · visual demo only</span>' : '<span class="caption">Move your pointer over the orb</span>'}`, `.orb{width:130px;height:130px;border-radius:50%;position:relative;background:radial-gradient(circle at 30% 24%,#ffffffba,transparent 24%),radial-gradient(circle at 72% 70%,${c},transparent 65%),${b};box-shadow:inset -18px -12px 28px #0009,inset 2px 3px 7px #fff8,0 10px 45px ${b}66;isolation:isolate;transition:transform .2s}.orb i{position:absolute;inset:10%;border-radius:45% 55% 65% 35%;background:conic-gradient(from 45deg,transparent,${a},transparent,${c},${a});filter:blur(9px);mix-blend-mode:screen;animation:orbFlow 9s linear infinite}.orb.listening i{animation-duration:1.7s}@keyframes orbFlow{50%{transform:rotate(180deg) scale(.75);border-radius:65% 35% 45% 55%}100%{transform:rotate(360deg)}}`, `const orb=document.querySelector('.orb');orb.onpointermove=e=>{if(reduced.matches)return;const r=orb.getBoundingClientRect();orb.style.transform='perspective(500px) rotateY('+((e.clientX-r.left-r.width/2)/7)+'deg)'};orb.onpointerleave=()=>orb.style.transform='';${id === "voice" ? "document.querySelector('#listen').onclick=e=>{const active=orb.classList.toggle('listening');e.currentTarget.setAttribute('aria-pressed',String(active));e.currentTarget.textContent=active?'Stop listening demo':'Start listening demo';document.querySelector('#status').textContent=active?'Listening · visual demo only':'Idle · visual demo only'};" : ""}`)));

const glassCSS = `.stage{background:radial-gradient(ellipse at 15% 10%,#b468a8,transparent 55%),radial-gradient(ellipse at 90% 90%,#4794ca,transparent 60%),#29284e}.glass{background:linear-gradient(120deg,#ffffff35,#ffffff0c);border:1px solid #ffffff55;box-shadow:inset 0 1px #ffffff80,0 15px 35px #0003;backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px);border-radius:20px}.glass small{color:#fff9}.glass button{background:#fff2}@supports not (backdrop-filter:blur(1px)){.glass{background:#343550}}`;
const glass: ComponentExample[] = [
  example("glass-notification", "Glass notification", "A dismissible notification with a translucent, softly lit surface.", "Glass", "glass", "CSS frosted glass", demo("Glass notification", `<div class="glass notice"><div><small>WORKSPACE · JUST NOW</small><h2>Your space is ready.</h2><p>Pick up where you left off.</p></div><button id="dismiss" aria-label="Dismiss notification">×</button></div><button id="restore" hidden>Show notification</button>`, `${glassCSS}.notice{width:min(330px,100%);padding:20px;display:flex;gap:12px;align-items:center}.notice p{font-size:12px;color:#fff9}.notice h2{font-size:18px}.notice button{padding:3px 10px;align-self:start}`, `const card=document.querySelector('.notice'),restore=document.querySelector('#restore');document.querySelector('#dismiss').onclick=()=>{card.hidden=true;card.style.display='none';restore.hidden=false;restore.focus()};restore.onclick=()=>{card.hidden=false;card.style.display='flex';restore.hidden=true;document.querySelector('#dismiss').focus()};`)),
  example("glass-navigation", "Glass navigation", "A floating navigation pill with selectable sections and a moving active state.", "Glass", "glass", "CSS frosted glass", demo("Glass navigation", `<nav class="glass row" aria-label="Demo sections"><button aria-current="page">Overview</button><button>Projects</button><button>Settings</button></nav><p id="section" role="status">Overview</p>`, `${glassCSS}nav{padding:7px;gap:2px!important}nav button{padding:10px;border:0;background:transparent!important;font-size:12px}nav button[aria-current]{background:#ffffff35!important;box-shadow:0 2px 8px #0002}`, `document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelector('[aria-current]')?.removeAttribute('aria-current');b.setAttribute('aria-current','page');document.querySelector('#section').textContent=b.textContent});`)),
  example("glass-switch", "Glass switch", "An accessible toggle with a translucent thumb and a clear on/off state.", "Glass", "glass", "CSS + native input", demo("Glass switch", `<label class="glass switch"><span>Focus mode</span><input id="toggle" type="checkbox" role="switch"><span class="track" aria-hidden="true"><i></i></span></label><span id="state" class="caption" role="status">Focus mode off</span>`, `${glassCSS}.switch{padding:22px;display:flex;align-items:center;gap:30px}.switch input{position:absolute;opacity:0;width:1px;height:1px}.track{width:56px;height:32px;border-radius:24px;background:#0004;border:1px solid #fff4;padding:3px;transition:background .25s}.track i{display:block;width:24px;height:24px;background:#ffffff90;border:1px solid #fffa;border-radius:50%;box-shadow:inset 1px 1px 2px white;transition:transform .25s}.switch input:checked+.track{background:#6d70ee}.switch input:checked+.track i{transform:translateX(23px)}.switch input:focus-visible+.track{outline:2px solid white;outline-offset:4px}`, `document.querySelector('#toggle').onchange=e=>document.querySelector('#state').textContent='Focus mode '+(e.target.checked?'on':'off');`)),
  example("glass-slider", "Glass slider", "A keyboard-accessible range control with a live value readout.", "Glass", "glass", "CSS + native input", demo("Glass slider", `<div class="glass slider"><label for="intensity">Ambient light <output id="value" for="intensity">60%</output></label><input id="intensity" type="range" min="0" max="100" value="60"></div>`, `${glassCSS}.slider{width:min(300px,100%);padding:24px}.slider label{display:flex;justify-content:space-between;margin-bottom:16px;font-size:13px}.slider input{width:100%;accent-color:#d4dcff;cursor:pointer;height:28px}.slider output{font-variant-numeric:tabular-nums;color:#dce3ff}`, `document.querySelector('#intensity').oninput=e=>document.querySelector('#value').value=e.target.value+'%';`)),
];

const loaderMarkup = {
  orbit: `<circle cx="60" cy="60" r="40" stroke="currentColor" opacity=".15"/><g class="rotate"><circle cx="60" cy="20" r="5" fill="currentColor"/><circle cx="60" cy="100" r="3" fill="currentColor" opacity=".5"/></g>`,
  radar: `<circle cx="60" cy="60" r="42" stroke="currentColor" opacity=".2"/><circle cx="60" cy="60" r="26" stroke="currentColor" opacity=".15"/><circle cx="60" cy="60" r="10" stroke="currentColor" opacity=".2"/><g class="rotate"><path d="M60 60 L60 18 A42 42 0 0 1 102 60 Z" fill="currentColor" opacity=".15"/><path d="M60 60 L60 18" stroke="currentColor"/></g>`,
  ripple: [0,1,2].map(i=>`<circle class="ripple" cx="60" cy="60" r="40" stroke="currentColor" style="animation-delay:-${i}s"/>`).join(""),
  wave: Array.from({length:13},(_,i)=>`<path class="bar" d="M${24+i*6} ${60-Math.sqrt(36*36-(i*6-36)**2)} V${60+Math.sqrt(36*36-(i*6-36)**2)}" stroke="currentColor" stroke-width="2" style="animation-delay:-${i*.1}s"/>`).join(""),
  dots: Array.from({length:12},(_,i)=>`<circle class="dot" cx="${60+35*Math.cos(i*Math.PI/6)}" cy="${60+35*Math.sin(i*Math.PI/6)}" r="3" fill="currentColor" style="animation-delay:-${i*.1}s"/>`).join(""),
  rings: [30,40,50].map((r,i)=>`<circle class="rotate" cx="60" cy="60" r="${r}" stroke="currentColor" stroke-width="2" stroke-dasharray="${r*2} ${r*5}" style="--period:${2+i};animation-direction:${i%2?'reverse':'normal'}"/>`).join(""),
};
const loaders = Object.entries(loaderMarkup).map(([id, markup]) => example(`loader-${id}`, {orbit:"Orbit loader",radar:"Radar sweep",ripple:"Ripple loader",wave:"Wave disc",dots:"Dot chase",rings:"Counter-rotating rings"}[id]!, "A compact status animation with adjustable speed and a static reduced-motion state.", "Loaders", "loaders", "SVG + CSS", demo(`${id} loader`, `<svg width="112" height="112" viewBox="0 0 120 120" fill="none" role="img" aria-label="Loading">${markup}</svg><div class="row"><span role="status">Working…</span><button id="speed" aria-label="Change animation speed">1× speed</button></div>`, `.stage{--speed:1;color:#eeeef4}.rotate{transform-origin:60px 60px;animation:spin calc(var(--period,3)*1s / var(--speed)) linear infinite}.ripple{transform-origin:60px 60px;animation:ripple calc(3s / var(--speed)) linear infinite}.dot,.bar{animation:light calc(1.2s / var(--speed)) ease-in-out infinite}@keyframes ripple{from{transform:scale(.1);opacity:1}to{transform:scale(1.2);opacity:0}}@keyframes light{50%{opacity:.15}}`, `let fast=false;document.querySelector('#speed').onclick=e=>{fast=!fast;document.querySelector('.stage').style.setProperty('--speed',fast?'2':'1');e.target.textContent=fast?'2× speed':'1× speed'};`)));

function shaderDemo(kind: "aurora" | "waves") {
  const fragment = `precision mediump float;uniform vec2 resolution;uniform float time;void main(){vec2 p=(gl_FragCoord.xy-.5*resolution)/resolution.y;float v=sin(p.x*5.+time*.5+sin(p.y*4.-time*.3));float w=sin(p.y*7.+time*.4+p.x*2.);float glow=${kind === "aurora" ? "pow(max(0.,1.-abs(p.y+.13*v)),7.)" : "pow(.5+.5*sin((p.y+.11*v)*35.+time*1.6),12.)"};vec3 col=mix(vec3(.05,.13,.23),vec3(.32,.72,.69),.5+.5*w);col=mix(vec3(.025,.03,.07),col,glow);gl_FragColor=vec4(col,1.);}`;
  return demo(`${kind} shader`, `<canvas aria-label="Animated abstract ${kind} background" role="img"></canvas><div class="shader-caption"><span class="caption">Procedural ${kind}</span><h2>A different atmosphere.</h2><p id="fallback" hidden>Static fallback · WebGL unavailable</p></div>`, `.stage{background:linear-gradient(135deg,#152a44,#425a69);min-height:100dvh}.stage canvas{position:absolute;inset:0;width:100%;height:100%;z-index:-1}.shader-caption{text-align:center;text-shadow:0 2px 18px #0008}.shader-caption h2{margin-top:8px;font-size:26px}`, `const canvas=document.querySelector('canvas'),gl=canvas.getContext('webgl',{alpha:false,antialias:false});if(!gl){document.querySelector('#fallback').hidden=false}else{const compile=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error('Shader compile failed');return s};const vs=compile(gl.VERTEX_SHADER,'attribute vec2 position;void main(){gl_Position=vec4(position,0.,1.);}'),fs=compile(gl.FRAGMENT_SHADER,${JSON.stringify(fragment)}),program=gl.createProgram();gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);gl.useProgram(program);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const loc=gl.getAttribLocation(program,'position');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);const size=gl.getUniformLocation(program,'resolution'),clock=gl.getUniformLocation(program,'time');let raf=0;function draw(t=0){const dpr=Math.min(devicePixelRatio,1.5),w=Math.round(innerWidth*dpr),h=Math.round(innerHeight*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h)}gl.uniform2f(size,w,h);gl.uniform1f(clock,reduced.matches?0:t/1000);gl.drawArrays(gl.TRIANGLES,0,6);if(!document.hidden&&!reduced.matches)raf=requestAnimationFrame(draw)}function resume(){cancelAnimationFrame(raf);if(!document.hidden)draw(performance.now())}document.addEventListener('visibilitychange',resume);reduced.addEventListener('change',resume);window.addEventListener('resize',resume);canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();cancelAnimationFrame(raf);canvas.hidden=true;document.querySelector('#fallback').hidden=false});window.addEventListener('pagehide',()=>{cancelAnimationFrame(raf);gl.deleteBuffer(buffer);gl.deleteProgram(program);gl.deleteShader(vs);gl.deleteShader(fs)},{once:true});draw();}`);
}
const spatial: ComponentExample[] = [
  example("spatial-cube", "Prismatic cube", "A slow-turning translucent cube with a pause control.", "3D & shaders", "threeui", "CSS 3D", demo("Prismatic cube", `<div class="scene"><div class="cube">${Array.from({length:6},(_,i)=>`<i style="transform:${['translateZ(40px)','rotateY(180deg) translateZ(40px)','rotateY(90deg) translateZ(40px)','rotateY(-90deg) translateZ(40px)','rotateX(90deg) translateZ(40px)','rotateX(-90deg) translateZ(40px)'][i]}"></i>`).join('')}</div></div><button id="pause" aria-pressed="false">Pause rotation</button>`, `.scene{perspective:450px;width:100px;height:100px;padding:10px}.cube{width:80px;height:80px;position:relative;transform-style:preserve-3d;animation:cube 14s linear infinite}.cube i{position:absolute;inset:0;background:linear-gradient(135deg,#aeafff55,#518fa422);border:1px solid #bcbdffb0}@keyframes cube{from{transform:rotateX(-25deg) rotateY(0deg)}to{transform:rotateX(335deg) rotateY(360deg)}}`, `document.querySelector('#pause').onclick=e=>{const b=e.currentTarget,paused=b.getAttribute('aria-pressed')!=='true';b.setAttribute('aria-pressed',String(paused));b.textContent=paused?'Resume rotation':'Pause rotation';document.querySelector('.cube').style.animationPlayState=paused?'paused':'running'};`)),
  example("spatial-card", "Perspective card", "A product card follows the pointer with restrained tilt and a moving highlight.", "3D & shaders", "threeui", "CSS 3D + pointer", demo("Perspective card", `<div class="product surface" tabindex="0"><span class="caption">FORM / 01</span><div class="shape"></div><div class="row"><h2>Objects of interest.</h2><span>↗</span></div></div>`, `.product{width:270px;max-width:100%;background:radial-gradient(circle at var(--x,50%) var(--y,25%),#6a698155,transparent 65%),#13141c;transition:transform .2s;transform-style:preserve-3d}.shape{width:65px;height:65px;margin:15px auto;border-radius:20px 40px 30px 40px;background:linear-gradient(135deg,#eff0f9,#514c6d);box-shadow:inset -10px -10px 10px #10102088;transform:translateZ(20px)}.product h2{font-size:16px}.product .row{justify-content:space-between}`, `const card=document.querySelector('.product');card.onpointermove=e=>{if(reduced.matches)return;const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;card.style.transform='perspective(700px) rotateX('+((.5-y)*14)+'deg) rotateY('+((x-.5)*14)+'deg)';card.style.setProperty('--x',x*100+'%');card.style.setProperty('--y',y*100+'%')};card.onpointerleave=()=>card.style.transform='';`)),
  example("shader-aurora", "Aurora field", "An original GPU shader for a gently shifting atmospheric background, with a static fallback.", "3D & shaders", "threeui", "WebGL shader", shaderDemo("aurora")),
  example("shader-waves", "Contour waves", "Fine luminous contours flow across a lightweight shader surface, with a static fallback.", "3D & shaders", "threeui", "WebGL shader", shaderDemo("waves")),
];

export const COMPONENT_EXAMPLES: ComponentExample[] = [...motion, ...orbs, ...glass, ...loaders, ...spatial];

/** Resolve a small stable marker server-side, keeping full source out of navigation URLs. */
export function componentReference(request: string): string {
  const ids = [...request.matchAll(/\[COMPONENT:([a-z0-9-]+)\]/g)].map((m) => m[1]);
  return [...new Set(ids)].slice(0, 3).flatMap((id) => {
    const item = COMPONENT_EXAMPLES.find((entry) => entry.id === id);
    if (!item) {
      const essential = COMPONENTS.find(entry => entry.id === id);
      const html = essential && componentPreview(id);
      return essential && html ? [`COMPONENT REFERENCE: ${essential.name}\nAdapt this IDÆVIA component to the existing project stack, preserve other content, scope styles and retain accessibility. Extract the relevant markup and behavior rather than replacing the project with this demo.\n${html}`] : [];
    }
    const source = COMPONENT_SOURCES.find((entry) => entry.id === item.source)!;
    return [`COMPONENT REFERENCE: ${item.name}\nOriginal IDÆVIA example inspired by ${source.url}. ${source.note}\nAdapt the implementation below into the user's selected stack and existing design. Preserve its interactions, accessibility and reduced-motion behavior. Extract the relevant markup, scoped styles and behavior; do not copy the document wrapper or Content-Security-Policy into an existing page. For component frameworks, scope selectors and clean up event listeners, observers and GPU resources on unmount. Do not replace the whole project with this standalone demo. Do not claim this is upstream source.\n${item.html}`];
  }).join("\n\n");
}
