import type { ComponentCategory, ComponentSource, ComponentExample } from "./component-examples";

const base = `*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:#090b12;color:#edf0fa;font:14px/1.5 system-ui,sans-serif}body{overflow-x:hidden}button,input{font:inherit}button{cursor:pointer;color:inherit;background:#ffffff12;border:1px solid #ffffff25;padding:9px 16px;border-radius:99px}button:focus-visible,a:focus-visible,input:focus-visible{outline:2px solid #b5b8ff;outline-offset:4px}.stage{min-height:100dvh;display:flex;align-items:center;justify-content:center;gap:18px;flex-direction:column;padding:24px;position:relative;isolation:isolate;overflow:hidden}h1,h2,p{margin:0}h2{font-size:20px;letter-spacing:-.04em}.caption{font-size:11px;color:#a3aec7;letter-spacing:.08em;text-transform:uppercase}.row{display:flex;gap:12px;align-items:center;justify-content:center}.surface{border:1px solid #ffffff25;border-radius:20px;background:#ffffff09;padding:22px}.muted{color:#a3aec7}svg{max-width:100%}a{color:inherit}button:hover{background:#ffffff24}@keyframes spin{to{transform:rotate(360deg)}}@keyframes breathe{50%{transform:scale(.88);opacity:.4}}@keyframes rise{from{transform:translateY(22px);opacity:0}to{transform:translateY(0);opacity:1}}`;

export function demo(name: string, body: string, css = "", js = "") {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data:; base-uri 'none'; form-action 'none'"><title>${name}</title><style>${base}${css}\n@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}}html[data-paused] *,html[data-paused] *::before,html[data-paused] *::after{animation-play-state:paused!important}</style></head><body><main class="stage">${body}</main><script>const reduced=matchMedia('(prefers-reduced-motion: reduce)');document.addEventListener('visibilitychange',()=>{document.documentElement.toggleAttribute('data-paused',document.hidden);});${js}</script></body></html>`;
}

export function example(id: string, name: string, description: string, category: ComponentCategory, source: ComponentSource, technology: string, html: string): ComponentExample {
  return { id, name, description, category, source, technology, html, prompt: `Add the ${name} component to my project: ${description} Match my existing design, preserve working features, respect reduced motion, and keep it responsive. [COMPONENT:${id}]` };
}
