import { PLANS, CREDIT_PACKS } from "./plans";

/** Preview copy only. Account events continue to use their actual account/payment data. */
export const EMAIL_EXAMPLES = [
  { id: "welcome", label: "Registration", kind: "welcome", subject: "Welcome to IDÆVIA Build", body: "Hi Alex,\n\nYour next idea has a home. Your IDÆVIA account is ready to turn a first prompt into a website or SaaS project.\n\nStart with an idea, choose a template, or explore components with live previews. Your agent will help you take the next step.\n\nNeed help getting started? Open the support icon in your workspace.", ctaLabel: "Create your first project", ctaUrl: "https://idaevia.app/app" },
  { id: "plan", label: "Plan purchase", kind: "payment", subject: `Your IDÆVIA ${PLANS.PRO.name} plan payment is confirmed`, body: `Hi Alex,\n\nYour payment of $${PLANS.PRO.price} USD for the ${PLANS.PRO.name} plan is confirmed. Your workspace is ready for your next project.\n\nYour plan includes ${PLANS.PRO.credits.toLocaleString("en-US")} monthly AI credits. Review your current balance and subscription in Settings & billing.\n\nPayment reference: example-payment-id\nKeep your payment provider’s receipt for tax and payment details.`, ctaLabel: "Open settings & billing", ctaUrl: "https://idaevia.app/app/settings" },
  { id: "topup", label: "Credit top-up", kind: "payment", subject: "Your credit top-up is confirmed", body: `Hi Alex,\n\nYour purchase of ${CREDIT_PACKS[0].credits} credits for $${CREDIT_PACKS[0].price} USD is confirmed. You can check your updated balance and continue your project in your workspace.\n\nPayment reference: example-payment-id\nYour projects and conversation history are ready when you are.`, ctaLabel: "Continue building", ctaUrl: "https://idaevia.app/app/projects" },
  { id: "password", label: "Password change", kind: "password", subject: "Your IDÆVIA password was changed", body: "Hi Alex,\n\nYour account password was changed. Your other sessions have been signed out.\n\nIf this was you, there is nothing else to do. If you did not make this change, contact info@idaevia.app immediately. We will never ask you to email your password.", ctaLabel: "Review account security", ctaUrl: "https://idaevia.app/app/profile?section=security" },
  { id: "promotion", label: "Promotion", kind: "promotion", subject: "Make room for your next big idea", body: "A new idea deserves room to grow.\n\n[Describe your real offer: the plan or credit pack, the exact benefit and who is eligible.]\n\n[Add the start/end dates, timezone, redemption instructions and any limitations. Configure the actual offer in your payment provider before sending.]\n\nExplore the offer and choose what fits your next project.", ctaLabel: "Explore the offer", ctaUrl: "https://idaevia.app/pricing", unsubscribe: "https://idaevia.app/email/unsubscribe" },
];
