/** Diagnostics are rule-based leads for an operator, never a claim of a verified root cause. */
export type ErrorArea = "PLATFORM" | "PROVIDER" | "PROJECT" | "UNKNOWN";
export type ErrorDiagnosis = { code: string; title: string; area: ErrorArea; severity: "CRITICAL" | "HIGH" | "MEDIUM"; explanation: string; steps: string[] };
export function diagnosePlatformError(source: string, text: string): ErrorDiagnosis {
  const result = (code: string, title: string, area: ErrorArea, severity: ErrorDiagnosis["severity"], explanation: string, steps: string[]): ErrorDiagnosis => ({ code, title, area, severity, explanation, steps });
  if (source.startsWith("provider-")) {
    const [, provider = "provider", kind = ""] = source.split("-");
    const name = provider === "anthropic" ? "Anthropic (Claude)" : provider === "openai" ? "OpenAI (GPT)" : provider;
    const billingUrl = provider === "anthropic" ? "console.anthropic.com → Plans & Billing" : "platform.openai.com → Billing";
    if (kind === "billing") return result("PROVIDER_BILLING", `${name} API account has no API credits`, "PROVIDER", "CRITICAL", `The platform's ${name} account cannot pay for requests. Generations fall back to the other provider while it is available; if both run out, every generation fails.`, [`Top up the ${name} account (${billingUrl}).`, "Open Platform errors → AI provider accounts and press “Check providers now” to confirm the account works again.", "Check the credit history of users who failed during the outage; failed runs were refunded automatically."]);
    if (kind === "auth") return result("PROVIDER_AUTH", `${name} API rejected the platform's API key`, "PROVIDER", "CRITICAL", `The ${name} API key was rejected. The key may have been rotated, revoked or misconfigured in the hosting environment.`, [`Check the ${name} API key in the hosting environment variables and the provider console.`, "Redeploy or update the environment, then press “Check providers now” in Platform errors.", "Never paste keys into support messages or incident notes."]);
    return result("PROVIDER_CAPACITY", `${name} API is rate-limited or overloaded`, "PROVIDER", "HIGH", `The ${name} API refused requests because of rate limits or overload. Requests fall back to the other provider while it is available.`, [`Check the ${name} console for rate limits and the current status page.`, "If this repeats at the same times, lower concurrency or request higher limits.", "No action is needed once the incident stops recurring."]);
  }
  if (source === "browser") return result("BROWSER_ERROR", "Platform interface error reported", "UNKNOWN", "MEDIUM", "A signed-in browser reported an interface error. Browser reports are unverified and can be affected by extensions or connection issues.", ["Reproduce the same screen with the current production release.", "Match the browser stack with server incidents at the same time.", "Check a clean browser session; do not treat a browser report as proof of a server outage."]);
  if (source.startsWith("billing")) return result("PAYMENT_PROCESSING", "Payment processing needs review", "PLATFORM", "CRITICAL", "A payment or credit operation failed. Its financial outcome must be checked before retrying manually.", ["Compare the provider event with Payments and the user's credit history.", "Check provider credentials, webhook delivery and database connectivity.", "Use the existing idempotent reconciliation flow. Do not grant credits twice."]);
  if (/heap out of memory|reached heap limit|\bENOMEM\b|out of memory|oom.kill|needs at least \d+ (?:MiB|GB)/i.test(text)) return result("RUNTIME_MEMORY", "Build or preview ran out of memory", "PLATFORM", "HIGH", "The runtime's memory budget was exhausted or its configured template is too small. Project size can also contribute.", ["Open the affected project's latest build log and reproduce the same build.", "Check the sandbox template RAM and Node heap limit; app runtimes require at least 4 GB.", "Reduce build concurrency or increase the isolated runtime capacity, then verify the public preview."]);
  if (/not configured|configure[ds]? (?:AI )?provider|E2B_API_KEY|missing.*(?:api.?key|credential)|invalid.*api.?key|authentication_error|\b401\b|\b403\b/i.test(text) && !/allowed hosts|external preview|project returned/i.test(text)) return result("PROVIDER_CONFIGURATION", "Provider configuration or access failed", source === "deploy" ? "PROJECT" : "PLATFORM", "HIGH", "A required service rejected authentication or is not configured. Check which account owns the integration.", ["Check the named provider's server-side credentials, permissions and enabled model/template.", "For a user-owned deployment integration, ask the owner to reconnect it in Integrations.", "Retry the failed operation once configuration is corrected; never paste keys into support messages."]);
  if (/quota|rate.limit|\b429\b|overloaded|insufficient.*(?:balance|funds)|credit balance/i.test(text)) return result("PROVIDER_CAPACITY", "Provider capacity or balance limit", "PROVIDER", "HIGH", "An upstream service reported a quota, rate or balance limit; this is different from a user's project-credit balance.", ["Check the AI/runtime/email provider's quota and account balance.", "Check whether several users failed at the same time; adjust concurrency or provider limits.", "Retry when capacity is available and verify any failed-generation credit adjustment."]);
  if (/allowed hosts|blocked request|external preview returned HTTP|project returned HTTP|No working preview|preview.*(?:not ready|could not start|failed to start)/i.test(text)) return result("PREVIEW_UNAVAILABLE", "Preview could not open", "UNKNOWN", "HIGH", "A working public preview was not confirmed. The server, port or allowed-host configuration may be responsible.", ["Open the admin project preview and latest runtime log.", "Check the start command, listening port, host 0.0.0.0 and exact allowed preview hostname.", "Verify the public preview URL after a successful build, including after a page reload."]);
  if (/Prisma|database.*(?:unavailable|connection|timed out)|connection.*(?:refused|pool)|\bP10\d\d\b|\bP20\d\d\b|ECONNREFUSED/i.test(text) && !/build|shell|preview|deploy/.test(source)) return result("DATABASE_FAILURE", "Platform database operation failed", "PLATFORM", "CRITICAL", "A platform database operation failed. The error code and surrounding operation need investigation.", ["Check database availability, connection-pool limits and deployment schema migrations.", "Inspect the matching server request using the incident time and reference.", "Restore database access before retrying payments or other state-changing operations."]);
  if (/ModuleNotFoundError|Cannot find module|Could not resolve|error TS\d+|Failed to compile|could not compile|SyntaxError|syntax error|Environment variable not found|Missing required environment/i.test(text) && /build|shell|preview|deploy/.test(source)) return result("PROJECT_BUILD", "Project source or configuration failed", "PROJECT", "MEDIUM", "The project failed a compiler, dependency or environment check. This does not by itself prove a platform outage.", ["Open the project and inspect its current Problems and build log.", "Use Debugger with the exact compiler error; verify dependencies and required project settings.", "Build again and verify Preview before marking this resolved."]);
  if (source.startsWith("email")) return result("EMAIL_DELIVERY", "Email delivery needs attention", "PROVIDER", "HIGH", "The mail worker or provider could not confirm delivery. The durable email queue retains its retry state.", ["Open Admin → Email and review the affected delivery status.", "Check sender-domain verification, API credentials and provider limits.", "For uncertain delivery, check the provider before retrying to avoid duplicate emails."]);
  if (source.startsWith("generation")) return result("AI_GENERATION", "AI generation did not complete", "UNKNOWN", "HIGH", "The AI response failed or could not be applied. The saved project and credit adjustment should be verified.", ["Open the project and compare the latest requested change with the last saved result.", "Check model availability, provider response format, output limits and timeout.", "Verify the failed run's credit adjustment, then retry with the same project context."]);
  if (/timeout|timed out|\b50[0234]\b|fetch failed|ECONNRESET/i.test(text)) return result("SERVICE_UNAVAILABLE", "Operation timed out or service unavailable", "PROVIDER", "HIGH", "A service request did not complete normally. Check the responsible service before changing application code.", ["Compare failures across users and check the provider's current health.", "Inspect server execution limits, provider latency and runtime capacity.", "Retry once the service recovers and confirm the result in the user's project."]);
  return result("UNEXPECTED_ERROR", "Unexpected operation failure", "UNKNOWN", "HIGH", "The operation failed; the available evidence does not establish a root cause yet.", ["Open the linked project or user and reproduce the same operation.", "Inspect the sanitized details and server logs using the incident reference and time.", "Verify the corrected operation before resolving; a recurrence will reopen this incident."]);
}

export function expectedOperationalError(error: unknown): boolean {
  if (!(error instanceof Error)) return false;
  return ["InsufficientCredits", "ProjectBusyError", "AuthError", "AbortError", "RuntimeCapacityError"].includes(error.constructor.name) || error.name === "AbortError" || /^(?:Admin access required|Support staff access required|A build is already running|Another connection is starting|You have 3 active|The runtime is no longer available|Stop the running command|The running command did not stop|Archive exceeds|There is no website to build)/i.test(error.message);
}

/** No request bodies, prompts, cookies, project source or whole provider response objects are accepted. */
export function redactIncidentText(input: string, secrets: string[] = []): string {
  let text = input.slice(0, 24000).replace(/\u001b\[[0-?]*[ -/]*[@-~]/g, "");
  for (const value of secrets.sort((a, b) => b.length - a.length)) if (value.length >= 4) text = text.replaceAll(value, "[redacted]");
  return text
    .replace(/\b(?:postgres(?:ql)?|mysql|mongodb(?:\+srv)?|redis):\/\/[^\s"'<>]+/gi, "[database URL]")
    .replace(/https?:\/\/[^\s"'<>]+/gi, value => { try { const url = new URL(value); return `${url.protocol}//${url.host}${url.pathname}${url.search ? '?[redacted]' : ''}`; } catch { return "[URL]"; } })
    .replace(/((?:authorization|cookie|set-cookie)\s*[:=]\s*)[^\r\n]+/gi, "$1[redacted]")
    .replace(/(["']?[\w.-]*(?:secret|token|password|api[_-]?key|client_secret)[\w.-]*["']?\s*[:=]\s*)(?:"[^"\r\n]*"|'[^'\r\n]*'|[^\s,;}]+)/gi, "$1[redacted]")
    .replace(/\bBearer\s+[^\s,;"']+/gi, "Bearer [redacted]")
    .replace(/\b(?:sk[-_](?:live_|test_|proj-|ant-)?|gh[pousr]_|github_pat_|whsec_|re_)[A-Za-z0-9_-]{12,}/g, "[redacted]")
    .replace(/\beyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\b/g, "[redacted JWT]")
    .replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi, "[email]")
    .slice(0, 8000);
}

export function diagnosticExcerpt(log: string): string {
  // Keep diagnostic lines, not full terminal output (which can contain application data).
  return log.split(/[\r\n]+/).filter(line => /error|failed|exception|heap|memory|ENOMEM|unavailable|timeout|timed out|quota|not found|cannot find|could not|\bTS\d+\b/i.test(line)).slice(-20).map(line => line.slice(0, 500)).join("\n");
}
