/** Detailed, editable project briefs. Each stays within the generator's 8,000-character limit. */
const quality = `DESIGN & INTERACTION
Choose a cohesive visual direction suited to this audience: a clear type scale, restrained colour palette, consistent spacing and a distinct hero. Design complete layouts at 390px, 768px and 1440px. Include a polished navbar with an accessible mobile menu, visible focus states and working navigation. Use purposeful motion with reduced-motion support. Provide loading, empty, success, validation and error states wherever relevant. Write specific, credible copy; label sample testimonials, metrics and images instead of inventing proof. Do not leave dead buttons or links.

DELIVERY & VALIDATION
Preserve working features in an existing project. Choose suitable languages/frameworks and explain the recommendation; honour any stack I specify. Build editable source files with clear boundaries between UI, data and integrations. Use semantic markup, labelled inputs, keyboard navigation and sufficient contrast. Optimise images and avoid unnecessary dependencies. Check the key flows and responsive layouts, then explain what was implemented, what was tested and any remaining setup. Never claim a real payment, email, booking or deployment succeeded without a configured integration.`;

export function websiteBrief(title: string, direction: string) {
  return `Build a complete ${title.toLowerCase()} project. Make it feel like a real business website, with a strong identity and a clear visitor journey. Use a sensible fictional brand that I can rename, English copy by default, and make the content easy to edit.

PROJECT DIRECTION
${direction}

PAGES & CONVERSION
Plan the information hierarchy around one primary conversion. Include a useful hero with a concrete headline and clear CTA; supporting benefits with visual examples; relevant services or product details; transparent pricing where appropriate; trust and FAQ sections; and a footer with useful navigation. Add dedicated detail pages where the subject needs them. Connect primary CTAs to the intended form or next step. Forms need inline validation, accessible feedback and spam-resistant server handling if a backend is included. If an integration is not connected, make that state honest and provide setup instructions. Include per-page titles, descriptions, social previews and structured data only for verified facts.

${quality}`;
}

export function saasBrief(title: string, audience: string, flows: string, data: string) {
  return `Build a complete ${title} SaaS MVP for ${audience}. This is an application with working user journeys and persistent data, plus a public marketing website. Start with the core workflow and deliver it end to end. If my chosen runtime cannot run the backend, still provide the native source and clearly explain the required runtime.

PRODUCT & USER JOURNEYS
${flows}

DATA & BACKEND
Model ${data}. Use a relational schema with migrations, indexes and validated server endpoints. Recommend an appropriate frontend, backend and database; Next.js with TypeScript and PostgreSQL is a reasonable default when I do not choose a stack. Support my language/framework preference. Include authentication, password recovery through a configurable provider, organisation/workspace membership, owner/admin/member permissions and server-side tenant checks on every read and mutation. Never trust tenant or owner IDs from the browser. Seed clearly labelled demo data. Store secrets only in environment variables and document .env.example. Include pagination, filters, sorting and meaningful errors. Avoid exposing credentials in logs or generated previews.

APP SCREENS & BUSINESS MODEL
Provide onboarding, an overview dashboard, list/detail/create/edit flows for the core records, account settings and workspace settings. Show loading, empty and permission-denied states. Make destructive actions explicit and recoverable where possible. Add a public homepage explaining the product, a feature walkthrough, pricing and FAQ. If subscriptions are required, use configurable checkout and verified idempotent webhooks; keep test/demo billing clearly marked until real credentials are configured. Do not build fake analytics, simulated sends or decorative dashboards that imply real operations.

${quality}

ACCEPTANCE CRITERIA
A new user can sign up, complete onboarding, create a workspace, complete the central workflow, reload and see saved data. A second user cannot read or change the first user's records. Validate duplicate submissions and failed requests. Provide setup, build and run commands, integration prerequisites and a concise list of remaining limitations.`;
}

export const SAAS_BRIEFS = [
  { id: "crm-app", title: "Sales CRM", audience: "small B2B sales teams", flows: "Capture leads manually or by CSV, validate imports, group contacts by company, qualify opportunities and move deals through a configurable pipeline. Each deal needs an owner, value, stage, notes, activity timeline and next task. Include search, filtering, overdue follow-ups and a useful pipeline summary. Drag-and-drop must have a keyboard/menu alternative.", data: "organisations, members, companies, contacts, deals, stages, notes, tasks and audit events" },
  { id: "project-management-app", title: "Project management", audience: "agencies collaborating with clients", flows: "Create a project from a template, invite members with roles, create tasks with assignees, due dates and labels, switch between list and kanban views, and discuss work in task comments. Show project progress computed from real tasks. Support a read-only client view, notification preferences and overdue reminders through a configurable email provider.", data: "workspaces, memberships, projects, tasks, labels, comments, invitations and notifications" },
  { id: "booking-app", title: "Scheduling & bookings", audience: "service businesses managing appointments", flows: "Let an owner configure services, duration, buffer times, staff schedules, time zones and cancellation rules. Customers choose a service and a real available slot, enter details and receive a booking confirmation. Prevent double booking in a database transaction. Staff can reschedule, cancel or mark attendance. Provide a calendar and accessible list view; expose customer-facing booking pages without exposing private staff data.", data: "businesses, staff, services, availability rules, blackout dates, customers and bookings" },
  { id: "helpdesk-app", title: "Customer support desk", audience: "teams supporting multiple products", flows: "Customers submit a ticket with category and priority, track its status and reply in a conversation. Agents use a queue with assignment, search, filters and internal notes that customers cannot read. Include saved replies, escalation, resolution and reopening. Persist messages and deliver updates across separate browsers; disclose offline or reconnecting states. Add a searchable knowledge base.", data: "organisations, customers, agents, tickets, public replies, internal notes, categories and knowledge articles" },
  { id: "invoicing-app", title: "Invoicing & expenses", audience: "freelancers and small agencies", flows: "Create clients, draft itemised invoices, apply configurable tax and discounts, preview and download PDFs, and record verified payments or explicitly marked manual payments. Include invoice numbering, draft/sent/paid/overdue status, expense entry and currency-aware totals. Use integer minor units or exact decimal arithmetic; never mix currencies in a total. Provide exportable reports without claiming to replace professional accounting advice.", data: "businesses, clients, invoices, invoice items, taxes, payments, expenses and currencies" },
  { id: "analytics-app", title: "Product analytics", audience: "SaaS founders understanding product usage", flows: "Provide a documented event ingestion endpoint with project keys, input limits and validation. Show date-filtered event counts, active users, funnels and retention derived from stored events. Include a demo dataset visibly labelled as demo. Explain event naming, consent integration and retention controls. Make charts readable with table alternatives, empty states and clear metric definitions.", data: "workspaces, projects, hashed API keys, events, anonymous identities, funnels and saved reports" },
  { id: "learning-app", title: "Course platform", audience: "educators selling structured online courses", flows: "An instructor drafts courses, organises modules and lessons, adds media references and quizzes, then publishes. Students enrol, resume lessons, track progress and review quiz results. Restrict paid lessons to verified enrolments. Include a public catalogue, course detail page, instructor dashboard and learner dashboard. Do not expose private lesson assets through an unprotected URL.", data: "organisations, instructors, courses, modules, lessons, quizzes, attempts, enrolments and progress" },
  { id: "inventory-app", title: "Inventory management", audience: "small retailers managing stock across locations", flows: "Create products with SKUs and variants, manage suppliers and warehouses, receive purchase orders, transfer stock and record adjustments with reasons. Show low-stock alerts and movement history. Prevent inconsistent or negative stock using transactional checks; define an explicit backorder policy. Offer CSV import with row-level validation and export.", data: "organisations, products, variants, suppliers, warehouses, purchase orders, stock balances and movements" },
  { id: "recruitment-app", title: "Recruitment pipeline", audience: "growing teams hiring across departments", flows: "Publish job listings, receive candidate applications, review consent and attachments, move applicants through stages, schedule interviews and collect private interviewer feedback. Include role-specific access and a candidate-facing status page. Provide search, rejection templates and configurable data-retention controls. Never fabricate scoring or automatically reject people based on sensitive traits.", data: "organisations, departments, jobs, candidates, applications, stages, interviews and feedback" },
  { id: "social-planner-app", title: "Content calendar", audience: "marketing teams planning multiple brands", flows: "Create brands and channels, draft posts, organise a calendar, collect review comments, request approval and schedule approved content. Include media metadata and a reusable asset library. Keep scheduling distinct from actual publishing: connect provider APIs through secure OAuth before sending real posts, show delivery errors and provide safe retry/idempotency. Add calendar and accessible list views.", data: "workspaces, brands, channels, posts, assets, approval requests, schedules and publish attempts" },
  { id: "membership-app", title: "Membership community", audience: "creators running paid communities", flows: "Visitors browse membership tiers and join through configured billing. Members access discussion spaces, create posts, comment, RSVP to events and edit profiles. Moderators review reports and manage content with audit history. Protect member-only content on the server and verify subscription events before granting access. Add search, notification preferences and a simple onboarding checklist.", data: "communities, memberships, tiers, spaces, posts, comments, events, RSVPs and moderation reports" },
  { id: "ai-workspace-app", title: "AI document workspace", audience: "teams summarising and searching their own documents", flows: "Users upload supported documents with size limits, see ingestion progress, search their workspace and ask questions with citations to actual document passages. Isolate vector/search queries by tenant and enforce file permissions before retrieval. Provide a grounded cannot-answer state when evidence is missing. Show provider configuration and usage limits, allow deletion and avoid sending secrets or unrelated tenants' documents to the model.", data: "workspaces, members, documents, extracted passages, ingestion jobs, conversations, citations and usage records" },
];
