"use client";
import { useCallback, useEffect, useState } from "react";
type Campaign = { id: string; subject: string; body: string; ctaLabel?: string; ctaUrl?: string; plan?: string; status: string; _count: { deliveries: number } };
type Data = { config: { enabled: boolean; from: string; replyTo: string; hasKey: boolean }; subscribers: number; campaigns: Campaign[]; counts: { status: string; _count: number }[]; deliveries: { id: string; subject: string; kind: string; status: string; lastError: string | null; createdAt: string; user: { email: string } }[] };
async function api(path: string, method = "GET", body?: unknown) {
  const response = await fetch(path, { method, headers: { "Content-Type": "application/json" }, ...(body ? { body: JSON.stringify(body) } : {}) });
  const data = await response.json(); if (!response.ok) throw new Error(data.error || "Email action failed."); return data;
}
const stateLabel = (state: string) => ({ SENT: "Accepted by provider", PENDING: "Queued", SENDING: "Sending", FAILED: "Rejected", REVIEW: "Check provider", SUPPRESSED: "Not sent" }[state] || state);
export function EmailAdmin() {
  const [data, setData] = useState<Data | null>(null), [error, setError] = useState(""), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false);
  const [config, setConfig] = useState({ enabled: false, from: "IDÆVIA <support@idaevia.app>", replyTo: "support@idaevia.app", apiKey: "" });
  const [draft, setDraft] = useState({ subject: "", body: "", ctaLabel: "", ctaUrl: "", plan: "" });
  const [preview, setPreview] = useState<{ html: string; recipients: number; campaign?: Campaign } | null>(null);
  const refresh = useCallback(async (initial = false) => { const next = await api("/api/admin/email") as Data; setData(next); if (initial) setConfig({ enabled: next.config.enabled, from: next.config.from, replyTo: next.config.replyTo, apiKey: "" }); }, []);
  useEffect(() => { let active = true; api("/api/admin/email").then((next: Data) => { if (active) { setData(next); setConfig({ enabled: next.config.enabled, from: next.config.from, replyTo: next.config.replyTo, apiKey: "" }); } }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, []);
  async function action(work: () => Promise<void>) { setBusy(true); setError(""); setNotice(""); try { await work(); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Please try again."); } finally { setBusy(false); } }
  const payload = { ...draft, ctaLabel: draft.ctaLabel || undefined, ctaUrl: draft.ctaUrl || undefined, plan: draft.plan || undefined };
  return <div className="max-w-6xl space-y-8">
    {error && <p role="alert" className="text-sm text-red-500">{error}</p>}{notice && <p role="status" className="text-sm text-signal-soft">{notice}</p>}
    <section className="card p-6"><h2 className="font-medium text-lg">Email delivery</h2><p className="text-sm text-ash mt-2">{data?.config.enabled && data.config.hasKey ? "Email sending is enabled. Send a test to verify the sender and inbox delivery." : "Not connected. Account notifications stay queued until you enable a verified sender."}</p>
      <form className="mt-5 grid md:grid-cols-2 gap-4" onSubmit={event => { event.preventDefault(); void action(async () => { await api("/api/admin/email", "PUT", { ...config, apiKey: config.apiKey || undefined }); setConfig(c => ({ ...c, apiKey: "" })); setNotice("Email configuration saved."); }); }}>
        <label className="text-sm">Sender<input className="input w-full mt-1" value={config.from} onChange={event => setConfig({ ...config, from: event.target.value })} placeholder="IDÆVIA <hello@your-domain.com>" required /></label><label className="text-sm">Reply-to address<input type="email" className="input w-full mt-1" value={config.replyTo} onChange={event => setConfig({ ...config, replyTo: event.target.value })} required /></label><label className="text-sm">Resend API key<input type="password" autoComplete="new-password" className="input w-full mt-1" value={config.apiKey} onChange={event => setConfig({ ...config, apiKey: event.target.value })} placeholder={data?.config.hasKey ? "Stored securely · leave blank to keep" : "re_…"} /></label><div className="self-end"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={config.enabled} onChange={event => setConfig({ ...config, enabled: event.target.checked })} />Enable email sending</label><p className="text-xs text-ash mt-2">Verify the sender domain in Resend first. API keys are encrypted and never returned to the browser.</p></div><div className="flex flex-wrap gap-2"><button className="btn btn-primary btn-sm" disabled={busy}>Save configuration</button><button type="button" className="btn btn-ghost btn-sm" disabled={busy || !data?.config.enabled} onClick={() => void action(async () => { const result = await api("/api/admin/email", "POST", { action: "test" }); setNotice(`Test queued for your admin email. ${result.processed} email(s) accepted in this batch; check the delivery log and your inbox.`); })}>Send test to my email</button></div>
      </form><p className="text-xs text-ash mt-4">Account events trigger delivery immediately. Failed attempts are retried on later queue runs; the daily scheduled run also checks pending mail. Use Process queue for immediate retries or remaining campaign batches.</p>
    </section>
    <section><div className="flex items-center justify-between mb-4"><div><h2 className="text-lg font-medium">Promotions</h2><p className="text-sm text-ash">{data?.subscribers ?? 0} {data?.subscribers === 1 ? "user" : "users"} opted in. Every promotional email includes unsubscribe.</p></div></div>
      <form className="card p-5 space-y-4" onSubmit={event => { event.preventDefault(); void action(async () => { await api("/api/admin/email/campaigns", "POST", { action: "draft", ...payload }); setNotice("Draft saved. Review it before sending."); setPreview(null); }); }}><div className="grid md:grid-cols-2 gap-4"><label className="text-sm">Subject<input required minLength={3} maxLength={150} className="input w-full mt-1" value={draft.subject} onChange={event => setDraft({ ...draft, subject: event.target.value })} /></label><label className="text-sm">Audience<select className="input w-full mt-1" value={draft.plan} onChange={event => setDraft({ ...draft, plan: event.target.value })}><option value="">All opted-in users</option>{["FREE", "STARTER", "PRO", "MAX", "AGENCY"].map(plan => <option key={plan}>{plan}</option>)}</select></label></div><label className="block text-sm">Message<textarea required minLength={20} maxLength={10000} rows={6} className="input w-full mt-1" value={draft.body} onChange={event => setDraft({ ...draft, body: event.target.value })} placeholder="Describe the offer, who it is for and any dates or limitations…" /></label><div className="grid md:grid-cols-2 gap-4"><label className="text-sm">Button label (optional)<input maxLength={60} className="input w-full mt-1" value={draft.ctaLabel} onChange={event => setDraft({ ...draft, ctaLabel: event.target.value })} /></label><label className="text-sm">Button link (HTTPS)<input type="url" className="input w-full mt-1" value={draft.ctaUrl} onChange={event => setDraft({ ...draft, ctaUrl: event.target.value })} /></label></div><div className="flex gap-2"><button className="btn btn-primary btn-sm" disabled={busy}>Save draft</button><button type="button" className="btn btn-ghost btn-sm" disabled={busy} onClick={() => void action(async () => { setPreview(await api("/api/admin/email/campaigns", "POST", { action: "preview", ...payload })); })}>Preview</button></div></form>
      <div className="mt-4 divide-y divide-graphite">{data?.campaigns.map(campaign => <div key={campaign.id} className="py-4 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-medium">{campaign.subject}</p><p className="text-xs text-ash">{campaign.status} · {campaign.plan || "All plans"} · {campaign._count.deliveries} queued recipients</p></div><div className="flex gap-2">{campaign.status === "DRAFT" && <button disabled={busy} className="btn btn-ghost btn-sm" onClick={() => void action(async () => { const rendered = await api("/api/admin/email/campaigns", "POST", { action: "preview", subject: campaign.subject, body: campaign.body, ctaLabel: campaign.ctaLabel || undefined, ctaUrl: campaign.ctaUrl || undefined, plan: campaign.plan || undefined }); setPreview({ ...rendered, campaign }); })}>Review & send</button>}{campaign.status !== "CANCELLED" && <button disabled={busy} className="btn btn-ghost btn-sm" onClick={() => void action(async () => { await api("/api/admin/email/campaigns", "POST", { action: "cancel", id: campaign.id }); setPreview(null); setNotice("Unsent campaign emails cancelled. Messages already in transit cannot be recalled."); })}>Cancel</button>}</div></div>)}</div>
      {preview && <section className="card p-5 mt-4"><div className="flex justify-between gap-3 mb-3"><h3 className="font-medium">Preview · {preview.recipients} eligible recipients</h3><button className="btn btn-ghost btn-sm" onClick={() => setPreview(null)}>Close preview</button></div><iframe title="Email preview" sandbox="" referrerPolicy="no-referrer" className="w-full h-[520px] rounded-lg bg-white" srcDoc={preview.html} />{preview.campaign && <button className="btn btn-primary btn-sm mt-4" disabled={busy || !preview.recipients || !data?.config.enabled} onClick={() => void action(async () => { const result = await api("/api/admin/email/campaigns", "POST", { action: "send", id: preview.campaign!.id, expectedRecipients: preview.recipients }); setNotice(`${result.queued} promotional emails queued.`); setPreview(null); })}>Send to {preview.recipients} opted-in users</button>}</section>}
    </section>
    <section><div className="flex flex-wrap justify-between items-center gap-3 mb-3"><h2 className="text-lg font-medium">Recent deliveries</h2><div className="flex gap-2"><button className="btn btn-ghost btn-sm" disabled={busy} onClick={() => void action(async () => {})}>Refresh</button><button className="btn btn-ghost btn-sm" disabled={busy || !data?.config.enabled} onClick={() => void action(async () => { const result = await api("/api/admin/email", "POST", { action: "process" }); setNotice(result.busy ? "A worker is already processing the queue." : `${result.processed} email(s) accepted by the provider.`); })}>Process queue</button></div></div><p className="text-xs text-ash mb-4">{data?.counts.map(count => `${stateLabel(count.status)}: ${count._count}`).join(" · ") || "No email events yet."}</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-graphite"><th className="py-3">Recipient</th><th>Subject</th><th>Status</th><th /></tr></thead><tbody>{data?.deliveries.map(mail => <tr key={mail.id} className="border-b border-graphite"><td className="py-3 pr-4 text-xs">{mail.user.email}</td><td className="pr-4"><p>{mail.subject}</p><p className="text-xs text-ash">{mail.kind} · {new Date(mail.createdAt).toLocaleString()}</p></td><td><p className="text-xs">{stateLabel(mail.status)}</p>{mail.lastError && <p className="text-xs text-ash max-w-xs mt-1">{mail.lastError}</p>}</td><td>{mail.status === "FAILED" && <button disabled={busy} className="btn btn-ghost btn-sm" onClick={() => void action(async () => { await api("/api/admin/email", "POST", { action: "retry", id: mail.id }); })}>Retry</button>}</td></tr>)}</tbody></table></div><p className="text-xs text-ash mt-3">“Accepted by provider” confirms API acceptance, not inbox delivery. Check Resend for delivery and bounce details.</p></section>
  </div>;
}
