"use client";
import { useEffect, useRef, useState } from "react";
import { PROMPT_LIBRARY, PROMPT_PACKS } from "@/lib/library";
import { UseInProject } from "./UseInProject";
export function PromptLibrary() {
  const [category, setCategory] = useState("All prompts");
  const [query, setQuery] = useState("");
  const [title, setTitle] = useState("");
  const [draft, setDraft] = useState("");
  const [copied, setCopied] = useState("");
  const dialog = useRef<HTMLDialogElement>(null);
  const area = useRef<HTMLTextAreaElement>(null);
  useEffect(() => { if (title) dialog.current?.showModal(); else dialog.current?.close(); }, [title]);
  const filtered = PROMPT_LIBRARY.filter(item => (category === "All prompts" || item.category === category) && `${item.title} ${item.prompt}`.toLowerCase().includes(query.toLowerCase()));
  function edit(name: string, prompt: string) { setTitle(name); setDraft(prompt); setCopied(""); }
  return <div className="flex-1 overflow-y-auto p-6 space-y-8">
    <div className="max-w-3xl"><h2 className="text-2xl font-medium">Start with a complete brief.</h2><p className="text-sm text-ash mt-2">Detailed prompts for business websites, landing pages and working SaaS applications. Preview and customise the brand, audience, features and stack before using one.</p></div>
    <div className="catalog-toolbar"><input type="search" aria-label="Search prompts" className="input flex-1 min-w-48" placeholder="Try CRM, booking, portfolio or analytics…" value={query} onChange={event => setQuery(event.target.value)} /><select aria-label="Prompt category" className="input" value={category} onChange={event => setCategory(event.target.value)}>{["All prompts", ...new Set(PROMPT_LIBRARY.map(item => item.category))].map(name => <option key={name}>{name}</option>)}</select></div>
    <section><p role="status" className="text-xs text-ash mb-4">{filtered.length} prompts</p><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{filtered.map(item => <article key={item.id} className="card p-5 flex flex-col gap-3"><p className="label">{item.category}</p><h3 className="font-medium">{item.title}</h3><p className="text-xs text-ash line-clamp-4 flex-1">{item.prompt.split("\n\n")[0]}</p><p className="text-xs text-ash">{item.prompt.trim().split(/\s+/).length} words · editable brief</p><button className="btn btn-ghost btn-sm self-start" onClick={() => edit(item.title, item.prompt)}>Preview & customise</button></article>)}</div>{!filtered.length && <p className="card p-8 text-center text-ash">No matching prompts. Try another search or category.</p>}</section>
    <section><h2 className="font-medium mb-4">Launch packs</h2><div className="grid md:grid-cols-2 gap-4">{PROMPT_PACKS.map(pack => <article key={pack.id} className="card p-5"><h3 className="font-medium">{pack.name}</h3><p className="text-sm text-ash mt-2">{pack.description}</p><ol className="text-xs text-fog my-4 space-y-2">{pack.steps.map((step, i) => <li key={step.title}>{i + 1}. {step.title}</li>)}</ol><button className="btn btn-ghost btn-sm" onClick={() => edit(pack.name, pack.steps.map((step, i) => `${i + 1}. ${step.title}\n${step.prompt}`).join("\n\n"))}>Preview & customise pack</button></article>)}</div></section>
    <dialog ref={dialog} onClose={() => setTitle("")} aria-labelledby="prompt-title" className="m-auto w-[calc(100%-2rem)] max-w-3xl rounded-2xl border border-graphite bg-ink text-paper p-6 backdrop:bg-black/75"><div className="flex items-center justify-between gap-4 mb-3"><h2 id="prompt-title" className="font-medium">{title}</h2><button className="btn btn-ghost btn-sm" onClick={() => setTitle("")}>Close</button></div><p className="text-xs text-ash mb-4">Make this brief yours. Add your project name, preferred language/framework and any specific requirements.</p><textarea ref={area} aria-label="Editable project prompt" className="input w-full h-[50vh] text-sm leading-relaxed resize-none" maxLength={7800} value={draft} onChange={event => { setDraft(event.target.value); setCopied(""); }} /><div className="flex flex-wrap items-center justify-between gap-3 mt-4"><span role="status" className="text-xs text-ash">{copied || `${draft.length.toLocaleString()} / 7,800 characters`}</span><div className="flex gap-2"><button className="btn btn-ghost btn-sm" disabled={!draft.trim()} onClick={async () => { try { await navigator.clipboard.writeText(draft); setCopied("Copied"); } catch { area.current?.select(); setCopied("Select and copy with Ctrl+C or ⌘C."); } }}>Copy prompt</button>{draft.trim() && <UseInProject placement="top" prompt={draft} label="Use prompt" />}</div></div></dialog>
  </div>;
}
