import { PALETTES, renderSite, type SiteConfig } from "./engine";

const t = (c: SiteConfig) => c;

export const TEMPLATES: SiteConfig[] = [
  t({
    id: "saas-dark",
    name: "SaaS — Dark Signal",
    category: "SaaS",
    description: "Premium dark SaaS landing with pricing, testimonials and FAQ.",
    brand: "Nimbus",
    tagline: "The CRM your sales team will actually use.",
    subline: "Pipeline, email, calls and AI follow-ups in one fast workspace. Close more deals with less admin.",
    ctaPrimary: "Start free trial",
    ctaSecondary: "See how it works",
    nav: ["Features", "Pricing", "Testimonials", "FAQ"],
    palette: PALETTES.dark,
    fontDisplay: "Space Grotesk",
    fontBody: "Inter",
    heroImageSeed: "nimbus-dash",
    features: [
      { title: "Visual pipeline", text: "Drag deals between stages and see forecast update live." },
      { title: "AI follow-ups", text: "Draft replies from context, send in one click, never miss a lead." },
      { title: "Unified inbox", text: "Email, calls and notes on one timeline per contact." },
      { title: "Automations", text: "Trigger tasks, alerts and sequences without code." },
      { title: "Reports", text: "Win rate, cycle time and rep performance dashboards." },
      { title: "Integrations", text: "Slack, Gmail, Outlook, Stripe and 40+ tools." },
    ],
    stats: [
      { value: "12k+", label: "teams" },
      { value: "38%", label: "faster cycles" },
      { value: "99.99%", label: "uptime" },
      { value: "4.9★", label: "rating" },
    ],
    pricing: [
      { name: "Starter", price: "$19", period: "/user/mo", items: ["Pipeline", "Email sync", "Basic reports"] },
      { name: "Growth", price: "$49", period: "/user/mo", items: ["Everything in Starter", "AI follow-ups", "Automations", "Priority support"], featured: true },
      { name: "Enterprise", price: "Custom", period: "", items: ["SSO & SCIM", "Dedicated CSM", "Custom SLAs"] },
    ],
    testimonials: [
      { quote: "We replaced three tools and doubled reply rates in a month.", name: "Maya Chen", role: "Head of Sales, Loop" },
      { quote: "Finally a CRM that reps open every morning.", name: "Daniel Ortiz", role: "Founder, Brightside" },
      { quote: "The AI follow-ups alone paid for the plan.", name: "Ana Petrova", role: "RevOps, Klar" },
    ],
    faq: [
      { q: "Is there a free plan?", a: "Yes — 14 days free on any plan, no card required." },
      { q: "Can I import from HubSpot or Pipedrive?", a: "One-click import for contacts, deals and notes." },
      { q: "Do you offer annual billing?", a: "Yes, with two months free." },
    ],
  }),
  t({
    id: "agency",
    name: "Agency — Studio",
    category: "Agency",
    description: "Creative agency site with work gallery and services.",
    brand: "Northform",
    tagline: "We design brands and products people remember.",
    subline: "A senior studio for strategy, identity, web and product. Small team, big outcomes.",
    ctaPrimary: "Start a project",
    ctaSecondary: "View work",
    nav: ["Features", "Gallery", "Testimonials", "Contact"],
    palette: PALETTES.light,
    fontDisplay: "Manrope",
    fontBody: "Inter",
    heroImageSeed: "studio-work",
    features: [
      { title: "Brand identity", text: "Positioning, naming, logo and visual systems." },
      { title: "Web design", text: "Fast, accessible marketing sites that convert." },
      { title: "Product design", text: "UX research, prototyping and design systems." },
    ],
    gallery: true,
    testimonials: [
      { quote: "The rebrand lifted our conversion by 42%.", name: "Sara Lund", role: "CMO, Fjord" },
      { quote: "Fast, thoughtful, obsessed with detail.", name: "Ilir Hoxha", role: "CEO, Vela" },
      { quote: "They feel like part of our team.", name: "Tom Walker", role: "Founder, Pilot" },
    ],
  }),
  t({
    id: "startup",
    name: "Startup — Launch",
    category: "Startup",
    description: "Waitlist-style launch page with product benefits.",
    brand: "Orbit",
    tagline: "Your second brain for meetings.",
    subline: "Orbit records, summarises and turns every call into action items you can assign in Slack.",
    ctaPrimary: "Join the waitlist",
    ctaSecondary: "Watch demo",
    nav: ["Features", "FAQ", "Contact"],
    palette: PALETTES.midnight,
    fontDisplay: "Space Grotesk",
    fontBody: "Inter",
    heroImageSeed: "orbit-app",
    features: [
      { title: "Auto summaries", text: "Get the decisions and action items, not the transcript." },
      { title: "Works everywhere", text: "Zoom, Meet, Teams and in-person via mobile." },
      { title: "Private by default", text: "Your data is encrypted and never used for training." },
    ],
    faq: [
      { q: "When does it launch?", a: "Private beta opens next month. Waitlist members get in first." },
      { q: "Is there a free tier?", a: "Yes, up to 5 meetings a month." },
    ],
  }),
  t({
    id: "portfolio",
    name: "Portfolio — Minimal",
    category: "Portfolio",
    description: "Clean personal portfolio with gallery and contact.",
    brand: "Elena Ristova",
    tagline: "Product designer crafting calm, useful interfaces.",
    subline: "Ten years designing for fintech and health. Currently open to select freelance work.",
    ctaPrimary: "Get in touch",
    ctaSecondary: "See work",
    nav: ["Features", "Gallery", "Contact"],
    palette: PALETTES.sand,
    fontDisplay: "Manrope",
    fontBody: "Inter",
    heroImageSeed: "portrait-design",
    features: [
      { title: "UX & research", text: "Interviews, journey maps and testing." },
      { title: "UI systems", text: "Scalable design systems in Figma." },
      { title: "Prototyping", text: "High-fidelity, interactive prototypes." },
    ],
    gallery: true,
  }),
  t({
    id: "restaurant",
    name: "Restaurant — Bistro",
    category: "Restaurant",
    description: "Warm restaurant site with menu highlights and reservations.",
    brand: "Casa Lumen",
    tagline: "Slow food, warm light, good company.",
    subline: "Seasonal Mediterranean cooking in the heart of the old town. Open Tuesday to Sunday.",
    ctaPrimary: "Reserve a table",
    ctaSecondary: "See the menu",
    nav: ["Features", "Gallery", "Testimonials", "Contact"],
    palette: PALETTES.warm,
    fontDisplay: "Playfair Display",
    fontBody: "Inter",
    heroImageSeed: "bistro-food",
    features: [
      { title: "Seasonal menu", text: "Changes every six weeks with local producers." },
      { title: "Natural wines", text: "A curated list from small vineyards." },
      { title: "Private dining", text: "Room for 14 with a tasting menu." },
    ],
    gallery: true,
    testimonials: [
      { quote: "The best risotto I have had outside Milan.", name: "Marta K.", role: "Guest" },
      { quote: "Warm staff, perfect lighting, unforgettable dessert.", name: "Jon P.", role: "Guest" },
      { quote: "Our go-to for anniversaries.", name: "Lina & Aleks", role: "Regulars" },
    ],
  }),
  t({
    id: "hotel",
    name: "Hotel — Boutique",
    category: "Hotel",
    description: "Boutique hotel with rooms, gallery and booking CTA.",
    brand: "Villa Aurea",
    tagline: "A quiet boutique stay above the lake.",
    subline: "Twelve rooms, a heated infinity pool and breakfast on the terrace. Two hours from the city.",
    ctaPrimary: "Book your stay",
    ctaSecondary: "Explore rooms",
    nav: ["Features", "Gallery", "Pricing", "Contact"],
    palette: PALETTES.ocean,
    fontDisplay: "Playfair Display",
    fontBody: "Inter",
    heroImageSeed: "lake-hotel",
    features: [
      { title: "Lake-view rooms", text: "Floor-to-ceiling windows and linen bedding." },
      { title: "Spa & pool", text: "Sauna, massage and a heated infinity pool." },
      { title: "Farm breakfast", text: "Local eggs, bread and honey every morning." },
    ],
    gallery: true,
    pricing: [
      { name: "Garden room", price: "€140", period: "/night", items: ["Queen bed", "Garden view", "Breakfast"] },
      { name: "Lake suite", price: "€240", period: "/night", items: ["King bed", "Balcony", "Breakfast", "Spa access"], featured: true },
      { name: "Penthouse", price: "€420", period: "/night", items: ["Two bedrooms", "Private terrace", "Butler"] },
    ],
  }),
  t({
    id: "realestate",
    name: "Real Estate — Listings",
    category: "Real Estate",
    description: "Property agency with featured listings and contact.",
    brand: "Keystone Realty",
    tagline: "Find a home you’ll love coming back to.",
    subline: "Curated apartments and houses across the city, with honest advice from local agents.",
    ctaPrimary: "Book a viewing",
    ctaSecondary: "Browse listings",
    nav: ["Features", "Gallery", "Testimonials", "Contact"],
    palette: PALETTES.slate,
    fontDisplay: "Manrope",
    fontBody: "Inter",
    heroImageSeed: "modern-house",
    features: [
      { title: "Verified listings", text: "Every property visited and checked by us." },
      { title: "Mortgage help", text: "Partners for the best rates, no fees to you." },
      { title: "Fast paperwork", text: "Digital contracts and same-week closings." },
    ],
    gallery: true,
    stats: [
      { value: "1,200+", label: "homes sold" },
      { value: "18 days", label: "avg. to close" },
      { value: "4.9★", label: "client rating" },
      { value: "12", label: "local agents" },
    ],
  }),
  t({
    id: "fitness",
    name: "Fitness — Studio",
    category: "Fitness",
    description: "Gym / trainer landing with programs and pricing.",
    brand: "FORGE",
    tagline: "Train hard. Recover smart. Get results.",
    subline: "Strength coaching, small-group classes and nutrition plans built around your life.",
    ctaPrimary: "Start 7-day trial",
    ctaSecondary: "See programs",
    nav: ["Features", "Pricing", "Testimonials", "Contact"],
    palette: PALETTES.emerald,
    fontDisplay: "Space Grotesk",
    fontBody: "Inter",
    heroImageSeed: "gym-training",
    features: [
      { title: "Strength", text: "Progressive programs coached by certified trainers." },
      { title: "Conditioning", text: "45-minute sessions that fit before work." },
      { title: "Nutrition", text: "Simple meal plans you will actually follow." },
    ],
    pricing: [
      { name: "Classes", price: "€39", period: "/mo", items: ["8 classes", "App access"] },
      { name: "Unlimited", price: "€69", period: "/mo", items: ["Unlimited classes", "Nutrition plan", "Progress tracking"], featured: true },
      { name: "1:1 Coaching", price: "€149", period: "/mo", items: ["Weekly sessions", "Custom program", "Chat support"] },
    ],
    testimonials: [
      { quote: "Lost 9 kg and gained a habit.", name: "Nikola D.", role: "Member" },
      { quote: "Coaches who actually watch your form.", name: "Ema S.", role: "Member" },
      { quote: "Best decision this year.", name: "Filip T.", role: "Member" },
    ],
  }),
  t({
    id: "medical",
    name: "Medical — Clinic",
    category: "Healthcare",
    description: "Clinic site with services, trust stats and appointment form.",
    brand: "Vita Clinic",
    tagline: "Modern care, delivered with patience.",
    subline: "General medicine, dental and dermatology under one roof. Same-week appointments.",
    ctaPrimary: "Book appointment",
    ctaSecondary: "Our services",
    nav: ["Features", "Testimonials", "FAQ", "Contact"],
    palette: PALETTES.ocean,
    fontDisplay: "Manrope",
    fontBody: "Inter",
    heroImageSeed: "clinic-care",
    features: [
      { title: "General medicine", text: "Check-ups, labs and referrals." },
      { title: "Dental", text: "Hygiene, whitening, implants." },
      { title: "Dermatology", text: "Skin checks and aesthetic treatments." },
    ],
    stats: [
      { value: "25k", label: "patients" },
      { value: "14", label: "specialists" },
      { value: "< 3 days", label: "to appointment" },
      { value: "4.8★", label: "reviews" },
    ],
    faq: [
      { q: "Do you accept insurance?", a: "We work with all major insurers; bring your card." },
      { q: "Can I book online?", a: "Yes, use the form below or call us." },
    ],
  }),
  t({
    id: "legal",
    name: "Legal — Law Firm",
    category: "Legal",
    description: "Law firm with practice areas and consultation CTA.",
    brand: "Harlow & Vance",
    tagline: "Clear counsel for complex matters.",
    subline: "Corporate, real estate and employment law for founders and growing companies.",
    ctaPrimary: "Book a consultation",
    ctaSecondary: "Practice areas",
    nav: ["Features", "Testimonials", "Contact"],
    palette: PALETTES.slate,
    fontDisplay: "Playfair Display",
    fontBody: "Inter",
    heroImageSeed: "law-office",
    features: [
      { title: "Corporate", text: "Incorporation, fundraising, M&A." },
      { title: "Real estate", text: "Purchases, leases, disputes." },
      { title: "Employment", text: "Contracts, policies, litigation." },
    ],
    testimonials: [
      { quote: "Precise, fast and refreshingly plain-spoken.", name: "Mira J.", role: "Founder" },
      { quote: "Handled our Series A without drama.", name: "Kosta V.", role: "CEO" },
      { quote: "They think like business people.", name: "Lea M.", role: "COO" },
    ],
  }),
  t({
    id: "automotive",
    name: "Automotive — Service",
    category: "Automotive",
    description: "Car service / dealership with services and booking.",
    brand: "Apex Motors",
    tagline: "Service you can trust, prices you can see.",
    subline: "Certified technicians, transparent quotes and a loaner car while you wait.",
    ctaPrimary: "Book service",
    ctaSecondary: "Get a quote",
    nav: ["Features", "Pricing", "Contact"],
    palette: PALETTES.dark,
    fontDisplay: "Space Grotesk",
    fontBody: "Inter",
    heroImageSeed: "car-service",
    features: [
      { title: "Diagnostics", text: "Full electronic check in 30 minutes." },
      { title: "Tyres & brakes", text: "Fitted same day, all brands." },
      { title: "Detailing", text: "Interior and exterior, ceramic coating." },
    ],
    pricing: [
      { name: "Basic service", price: "€89", period: "", items: ["Oil & filter", "20-point check"] },
      { name: "Full service", price: "€189", period: "", items: ["Everything in Basic", "Brakes & fluids", "Diagnostics"], featured: true },
      { name: "Detailing", price: "€149", period: "", items: ["Interior", "Exterior", "Protection"] },
    ],
  }),
  t({
    id: "events",
    name: "Events — Conference",
    category: "Events",
    description: "Conference landing with tickets and speakers.",
    brand: "Signal Conf",
    tagline: "Two days on the future of building software.",
    subline: "40 speakers, 1,500 builders, one stage. Belgrade, 14–15 May.",
    ctaPrimary: "Get tickets",
    ctaSecondary: "See speakers",
    nav: ["Features", "Pricing", "FAQ", "Contact"],
    palette: PALETTES.purple,
    fontDisplay: "Space Grotesk",
    fontBody: "Inter",
    heroImageSeed: "conference-stage",
    features: [
      { title: "Talks", text: "AI, product and engineering leadership." },
      { title: "Workshops", text: "Hands-on sessions with limited seats." },
      { title: "Networking", text: "Dinners, hallway track and after-party." },
    ],
    pricing: [
      { name: "Early bird", price: "€199", period: "", items: ["All talks", "Lunch", "Party"] },
      { name: "Standard", price: "€299", period: "", items: ["All talks", "Workshops", "Lunch", "Party"], featured: true },
      { name: "Team (5)", price: "€1,190", period: "", items: ["5 standard tickets", "Reserved seating"] },
    ],
    faq: [
      { q: "Are talks recorded?", a: "Yes, ticket holders get recordings a week after." },
      { q: "Refunds?", a: "Full refund up to 30 days before the event." },
    ],
  }),
  t({
    id: "education",
    name: "Education — Course",
    category: "Education",
    description: "Online course landing with curriculum and pricing.",
    brand: "Frontend Mastery",
    tagline: "Become the engineer teams fight to hire.",
    subline: "A 10-week, project-based course on modern web development with live mentoring.",
    ctaPrimary: "Enroll now",
    ctaSecondary: "View curriculum",
    nav: ["Features", "Pricing", "Testimonials", "FAQ"],
    palette: PALETTES.light,
    fontDisplay: "Manrope",
    fontBody: "Inter",
    heroImageSeed: "course-laptop",
    features: [
      { title: "Projects", text: "Ship 5 portfolio-ready projects." },
      { title: "Mentoring", text: "Weekly live sessions and code review." },
      { title: "Community", text: "Private Discord with alumni and hiring partners." },
    ],
    pricing: [
      { name: "Self-paced", price: "€290", period: "", items: ["All modules", "Community"] },
      { name: "Mentored", price: "€890", period: "", items: ["All modules", "Live sessions", "Code review", "Certificate"], featured: true },
    ],
    testimonials: [
      { quote: "Got a job offer before finishing week 8.", name: "Stefan R.", role: "Alumni" },
      { quote: "Best money I spent on my career.", name: "Ivana P.", role: "Alumni" },
      { quote: "The projects are the real deal.", name: "Bojan K.", role: "Alumni" },
    ],
    faq: [{ q: "Do I need experience?", a: "Basic HTML/CSS/JS is enough. We start from fundamentals." }],
  }),
  t({
    id: "ecommerce",
    name: "E-commerce — Fashion",
    category: "E-commerce",
    description: "Fashion store landing with product grid.",
    brand: "Aster",
    tagline: "Everyday essentials, made to last.",
    subline: "Organic cotton, fair factories, timeless cuts. Free shipping over €80.",
    ctaPrimary: "Shop new arrivals",
    ctaSecondary: "Our story",
    nav: ["Features", "Gallery", "FAQ", "Contact"],
    palette: PALETTES.rose,
    fontDisplay: "Manrope",
    fontBody: "Inter",
    heroImageSeed: "fashion-studio",
    features: [
      { title: "Sustainable", text: "GOTS-certified organic cotton." },
      { title: "Free returns", text: "30 days, no questions asked." },
      { title: "Made fairly", text: "Living wages in every factory." },
    ],
    gallery: true,
    faq: [
      { q: "How long is shipping?", a: "2–4 business days in the EU." },
      { q: "Do you ship worldwide?", a: "Yes, duties included at checkout." },
    ],
  }),
  t({
    id: "creator",
    name: "Creator — Link in bio",
    category: "Creator",
    description: "Creator page with offers and community CTA.",
    brand: "Mila Makes",
    tagline: "Learn to build a creative business online.",
    subline: "Weekly videos, a private community and templates that help you ship your first product.",
    ctaPrimary: "Join the community",
    ctaSecondary: "Free resources",
    nav: ["Features", "Pricing", "Contact"],
    palette: PALETTES.purple,
    fontDisplay: "Space Grotesk",
    fontBody: "Inter",
    heroImageSeed: "creator-desk",
    features: [
      { title: "Videos", text: "New tutorial every Tuesday." },
      { title: "Templates", text: "Notion, Canva and Figma kits." },
      { title: "Community", text: "Weekly calls and feedback threads." },
    ],
    pricing: [
      { name: "Free", price: "€0", period: "", items: ["Newsletter", "Public videos"] },
      { name: "Member", price: "€9", period: "/mo", items: ["Community", "Templates", "Monthly call"], featured: true },
    ],
  }),
  t({
    id: "finance",
    name: "Finance — Fintech",
    category: "Finance",
    description: "Fintech app landing with trust stats.",
    brand: "Ledgerly",
    tagline: "Business banking that does your bookkeeping.",
    subline: "Accounts, cards and automatic categorisation, connected to your accountant.",
    ctaPrimary: "Open an account",
    ctaSecondary: "See pricing",
    nav: ["Features", "Pricing", "FAQ", "Contact"],
    palette: PALETTES.midnight,
    fontDisplay: "Manrope",
    fontBody: "Inter",
    heroImageSeed: "fintech-cards",
    features: [
      { title: "Instant accounts", text: "IBAN in minutes, no paperwork." },
      { title: "Smart cards", text: "Limits, virtual cards, receipts auto-matched." },
      { title: "Accounting sync", text: "Xero, QuickBooks and Excel export." },
    ],
    stats: [
      { value: "€2.1B", label: "processed" },
      { value: "60k", label: "businesses" },
      { value: "PCI DSS", label: "certified" },
      { value: "24/7", label: "support" },
    ],
    pricing: [
      { name: "Solo", price: "€0", period: "/mo", items: ["1 account", "1 card"] },
      { name: "Team", price: "€19", period: "/mo", items: ["5 users", "Unlimited cards", "Accounting sync"], featured: true },
    ],
    faq: [{ q: "Is my money safe?", a: "Funds are safeguarded with a licensed EU bank." }],
  }),
  t({
    id: "web3",
    name: "Web3 — Token",
    category: "Web3",
    description: "Token / protocol landing page.",
    brand: "Helios Protocol",
    tagline: "Yield that stays on-chain.",
    subline: "A transparent liquidity protocol with audited contracts and real-time proof of reserves.",
    ctaPrimary: "Launch app",
    ctaSecondary: "Read docs",
    nav: ["Features", "FAQ", "Contact"],
    palette: PALETTES.purple,
    fontDisplay: "Space Grotesk",
    fontBody: "Inter",
    heroImageSeed: "abstract-chain",
    features: [
      { title: "Audited", text: "Three independent audits, public reports." },
      { title: "Non-custodial", text: "Your keys, your assets, always." },
      { title: "Multi-chain", text: "Ethereum, Base and Arbitrum." },
    ],
    stats: [
      { value: "$410M", label: "TVL" },
      { value: "3", label: "audits" },
      { value: "0", label: "incidents" },
      { value: "28k", label: "wallets" },
    ],
    faq: [{ q: "Is there a token?", a: "HLS governs the protocol; there is no presale." }],
  }),
  t({
    id: "gaming",
    name: "Gaming — Studio",
    category: "Gaming",
    description: "Game studio / launch page with gallery.",
    brand: "Ember Forge",
    tagline: "Worlds worth getting lost in.",
    subline: "An independent studio making story-driven games. Our next title launches this winter.",
    ctaPrimary: "Wishlist now",
    ctaSecondary: "Watch trailer",
    nav: ["Features", "Gallery", "Contact"],
    palette: PALETTES.dark,
    fontDisplay: "Space Grotesk",
    fontBody: "Inter",
    heroImageSeed: "game-art",
    features: [
      { title: "Story first", text: "Branching narratives with consequences." },
      { title: "Hand-painted", text: "Every frame drawn by our artists." },
      { title: "Original score", text: "Recorded with a live orchestra." },
    ],
    gallery: true,
  }),
  t({
    id: "dashboard",
    name: "Dashboard — Admin",
    category: "SaaS",
    description: "Analytics dashboard landing with product screenshots.",
    brand: "Metrix",
    tagline: "Product analytics without the SQL.",
    subline: "Funnels, retention and revenue dashboards your whole team can build.",
    ctaPrimary: "Start for free",
    ctaSecondary: "Live demo",
    nav: ["Features", "Pricing", "Testimonials", "FAQ"],
    palette: PALETTES.slate,
    fontDisplay: "Manrope",
    fontBody: "Inter",
    heroImageSeed: "analytics-dash",
    features: [
      { title: "Funnels", text: "Find where users drop and why." },
      { title: "Retention", text: "Cohorts by any property." },
      { title: "Revenue", text: "MRR, churn and LTV in one view." },
      { title: "Alerts", text: "Slack alerts on anomalies." },
      { title: "Warehouse sync", text: "BigQuery and Snowflake." },
      { title: "Privacy", text: "EU hosting and cookieless mode." },
    ],
    pricing: [
      { name: "Free", price: "$0", period: "/mo", items: ["10k events", "3 dashboards"] },
      { name: "Growth", price: "$79", period: "/mo", items: ["1M events", "Unlimited dashboards", "Alerts"], featured: true },
      { name: "Scale", price: "Custom", period: "", items: ["Warehouse sync", "SSO", "SLA"] },
    ],
    testimonials: [
      { quote: "We killed three Looker dashboards in a week.", name: "Priya N.", role: "PM, Sona" },
      { quote: "Our marketing team finally self-serves.", name: "Luka B.", role: "Head of Data" },
      { quote: "Setup took an afternoon.", name: "Chris O.", role: "CTO" },
    ],
    faq: [{ q: "Do you support Segment?", a: "Yes, plus a native JS/iOS/Android SDK." }],
  }),
  t({
    id: "ai-platform",
    name: "AI — Platform",
    category: "AI",
    description: "AI product landing with dark premium feel.",
    brand: "Synth",
    tagline: "Support agents that resolve, not deflect.",
    subline: "Train an AI agent on your docs and past tickets. Resolves 60% of conversations end-to-end.",
    ctaPrimary: "Book a demo",
    ctaSecondary: "How it works",
    nav: ["Features", "Pricing", "Testimonials", "FAQ"],
    palette: PALETTES.dark,
    fontDisplay: "Space Grotesk",
    fontBody: "Inter",
    heroImageSeed: "ai-agent",
    features: [
      { title: "Trained on you", text: "Docs, tickets and product data." },
      { title: "Actions", text: "Refunds, plan changes, lookups." },
      { title: "Human handoff", text: "Seamless escalation with full context." },
    ],
    stats: [
      { value: "60%", label: "auto-resolved" },
      { value: "< 4s", label: "first response" },
      { value: "32", label: "languages" },
      { value: "SOC 2", label: "type II" },
    ],
    pricing: [
      { name: "Starter", price: "$99", period: "/mo", items: ["1k resolutions", "Web widget"] },
      { name: "Business", price: "$499", period: "/mo", items: ["10k resolutions", "Actions", "Slack & email"], featured: true },
      { name: "Enterprise", price: "Custom", period: "", items: ["SSO", "Dedicated model", "SLA"] },
    ],
    testimonials: [
      { quote: "CSAT went up while tickets went down.", name: "Hana M.", role: "Head of Support" },
      { quote: "Implemented in a week.", name: "Marko G.", role: "Ops" },
      { quote: "The actions are the killer feature.", name: "Jade L.", role: "CX Lead" },
    ],
    faq: [{ q: "Which models do you use?", a: "Best-in-class models routed per task, with your data never used for training." }],
  }),
];

export const TEMPLATE_MAP = new Map(TEMPLATES.map((t) => [t.id, t]));
export const TEMPLATE_CATEGORIES = Array.from(new Set(TEMPLATES.map((t) => t.category)));

export function renderTemplate(id: string) {
  const t = TEMPLATE_MAP.get(id);
  if (!t) return null;
  return renderSite(t);
}

export { renderSite, PALETTES };
export type { SiteConfig };
